### ISSUE TITLE
Upgrade to Vite 4

### ISSUE THREAD

**Issue by khalidabuhakmeh** [haiya6/vite-plugin-html-resolve-alias#8]
👋 Hello @haiya6,

Could you please update this plugin to support Vite 4? I did a force install, which seems to work with the latest version of Vite, but the package won't install without an `npm install --force`.

This package is great, and I'd love for more folks to use it. 

Cheers :)

**Comment by haiya6** [comment]
Thank you for your support of this packgae.

The upgrade work has been completed, you can install `vite-plugin-html-resolve-alias@1.0.3`
